(function () {
  'use strict';

  const STORAGE_KEY = 'trvkc.portfolio.cloud-cache.v2';
  const LEGACY_STORAGE_KEY = 'trvkc.portfolio.draft.v1';
  const SCHEMA_VERSION = 1;
  const ACCENTS = ['volt', 'cyan', 'magenta', 'amber'];

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function text(value, fallback, maxLength) {
    const cleaned = String(value == null ? '' : value).trim().slice(0, maxLength);
    return cleaned || fallback;
  }

  function id(value, fallback) {
    const cleaned = String(value == null ? '' : value)
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9_-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 80);
    return cleaned || fallback;
  }

  function url(value, fallback) {
    const candidate = text(value, fallback, 1000);
    if (candidate === '#') return '#';
    try {
      const parsed = new URL(candidate, window.location.href);
      if (parsed.protocol === 'http:' || parsed.protocol === 'https:') return parsed.href;
    } catch (_) {}
    return fallback;
  }

  function tags(value) {
    const source = Array.isArray(value) ? value : String(value || '').split(',');
    return source
      .map(function (tag) { return text(tag, '', 40).toUpperCase(); })
      .filter(Boolean)
      .slice(0, 8);
  }

  function accent(value) {
    return ACCENTS.indexOf(value) >= 0 ? value : 'volt';
  }

  function uniqueId(candidate, prefix, used, index) {
    let next = id(candidate, prefix + '-' + (index + 1));
    let suffix = 2;
    const base = next;
    while (used.has(next)) next = base + '-' + suffix++;
    used.add(next);
    return next;
  }

  function normalize(input) {
    const source = input && typeof input === 'object' ? input : {};
    const used = new Set();

    const tools = (Array.isArray(source.tools) ? source.tools : []).slice(0, 100).map(function (item, index) {
      const safe = item && typeof item === 'object' ? item : {};
      return {
        id: uniqueId(safe.id, 'tool', used, index),
        title: text(safe.title, 'Untitled project', 120),
        description: text(safe.description, 'No description yet', 320),
        url: url(safe.url, '#'),
        tags: tags(safe.tags),
        filename: text(safe.filename, 'project_' + (index + 1) + '.run', 100),
        status: text(safe.status, 'LIVE', 30).toUpperCase(),
        action: text(safe.action, './launch', 30),
        accent: accent(safe.accent)
      };
    });

    const creative = (Array.isArray(source.creative) ? source.creative : []).slice(0, 50).map(function (item, index) {
      const safe = item && typeof item === 'object' ? item : {};
      return {
        id: uniqueId(safe.id, 'creative', used, index),
        title: text(safe.title, 'Untitled work', 120),
        subtitle: text(safe.subtitle, 'Details coming soon', 160),
        platform: text(safe.platform, '', 80),
        url: url(safe.url, '#'),
        label: text(safe.label, 'CREATIVE', 60).toUpperCase(),
        icon: text(safe.icon, '✦', 16),
        accent: accent(safe.accent)
      };
    });

    return { schemaVersion: SCHEMA_VERSION, tools: tools, creative: creative };
  }

  function defaults() {
    return normalize(window.TRVKC_PORTFOLIO_DEFAULTS || { tools: [], creative: [] });
  }

  function get() {
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) return normalize(JSON.parse(raw));
      const legacy = window.localStorage.getItem(LEGACY_STORAGE_KEY);
      if (legacy) return normalize(JSON.parse(legacy));
    } catch (_) {}
    return defaults();
  }

  function save(value) {
    const clean = normalize(value);
    let persisted = false;
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(clean));
      persisted = true;
    } catch (_) {}
    return { data: clone(clean), persisted: persisted };
  }

  function reset() {
    let persisted = false;
    try {
      window.localStorage.removeItem(STORAGE_KEY);
      window.localStorage.removeItem(LEGACY_STORAGE_KEY);
      persisted = true;
    } catch (_) {}
    return { data: defaults(), persisted: persisted };
  }

  function hasDraft() {
    try {
      return window.localStorage.getItem(STORAGE_KEY) !== null ||
        window.localStorage.getItem(LEGACY_STORAGE_KEY) !== null;
    }
    catch (_) { return false; }
  }

  function publishSource(value) {
    const json = JSON.stringify(normalize(value), null, 2).replace(/</g, '\\u003c');
    return [
      '/* Published portfolio content. Generated by the hidden on-page editor. */',
      'window.TRVKC_PORTFOLIO_DEFAULTS = ' + json + ';',
      ''
    ].join('\n');
  }

  window.TRVKCPortfolio = Object.freeze({
    accents: ACCENTS.slice(),
    clone: clone,
    defaults: defaults,
    get: get,
    hasDraft: hasDraft,
    normalize: normalize,
    publishSource: publishSource,
    reset: reset,
    save: save,
    storageKey: STORAGE_KEY,
    legacyStorageKey: LEGACY_STORAGE_KEY
  });
})();
